project:
  type: website

website:
  title: "Occupation coding tools:<br> benchmark data & performance"
  sidebar:
    style: docked
    search: false
    contents:
      - text: Home
        href: index.qmd
      - text: Example data
        href: example_data.qmd
      - text: Demo & performance
        href: demos_performance.qmd
